const API_URL = require('../src/constants').API_URL;
const PACKAGE_VERSION = require('../src/constants').PACKAGE_VERSION;

const API_KEY = 'abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789';
const INVALID_API_KEY = 'TEST-KEY';
const API_VERSION_OVERRIDE = 2;
const SOURCE_ID = '012abc345def678abc901def';
const ASSETS_ENDPOINT = `assets/${SOURCE_ID}`;
const ASSETS_URL = apiVersion => `${ API_URL }/v${ apiVersion }/${ ASSETS_ENDPOINT }`;


module.exports = {
    API_URL: API_URL,
    PACKAGE_VERSION: PACKAGE_VERSION,
    API_KEY: API_KEY,
    INVALID_API_KEY: INVALID_API_KEY,
    API_VERSION_OVERRIDE: API_VERSION_OVERRIDE,
    SOURCE_ID: SOURCE_ID,
    ASSETS_ENDPOINT: ASSETS_ENDPOINT,
    ASSETS_URL: ASSETS_URL
};
